### ISSUE TITLE
Denote co-first authors

### ISSUE THREAD

**Issue by dewittpe** [CU-DBMI-Peds/phoenix#7]
From #6 
> Peter, in addition to these changes, would you please add the * co-first-author for Nelson and I in all the places where you include the paper reference? thanks

**Comment by tdbennett** [comment]
Weird... did issue number 8 vanish? Anyway, the README still needs to be updated in this vein. I'm fine with a parenthetical in the Description file. thanks

**Comment by dewittpe** [comment]
> Weird... did issue number 8 vanish? Anyway, the README still needs to be updated in this vein. I'm fine with a parenthetical in the Description file. thanks

#8 is the PR.  Github sequentially numbers issues and pull requests.  There will not be an issue number 8 in this repo as that number has been assigned to a pull request.

I'm not sure what you are seeing with respect to the README.  I see the following on the `document-first-authors` branch.

<img width="1018" alt="image" src="https://github.com/CU-DBMI-Peds/phoenix/assets/3136617/c84dd899-5609-4f9f-82f3-008429d5a0de">

I will add the parenthetical to the description file soon.

**Comment by dewittpe** [comment]
closed by #8
